# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inventory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inventory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\x12\tinventory\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n\x13\x41vailabilityRequest\x12\x10\n\x08train_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_stop_id\x18\x02 \x01(\t\x12\x12\n\nto_stop_id\x18\x03 \x01(\t\x12/\n\x0btravel_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nquota_type\x18\x05 \x01(\t\x12\x12\n\nclass_type\x18\x06 \x01(\t\"k\n\x14\x41vailabilityResponse\x12\x17\n\x0f\x61vailable_count\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x1b\n\x13prediction_accuracy\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x01\"\xb5\x01\n\x0bLockRequest\x12\x10\n\x08train_id\x18\x01 \x01(\t\x12\x14\n\x0c\x66rom_stop_id\x18\x02 \x01(\t\x12\x12\n\nto_stop_id\x18\x03 \x01(\t\x12/\n\x0btravel_date\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\r\n\x05\x63ount\x18\x05 \x01(\x05\x12\x12\n\nlock_token\x18\x06 \x01(\t\x12\x16\n\x0e\x65xpiry_seconds\x18\x07 \x01(\x05\"G\n\x0cLockResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07lock_id\x18\x02 \x01(\t\x12\x15\n\rerror_message\x18\x03 \x01(\t\"!\n\x0eReleaseRequest\x12\x0f\n\x07lock_id\x18\x01 \x01(\t\"\"\n\x0fReleaseResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"1\n\x11\x41llocationRequest\x12\x0f\n\x07lock_id\x18\x01 \x01(\t\x12\x0b\n\x03pnr\x18\x02 \x01(\t\";\n\x12\x41llocationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x14\n\x0cseat_numbers\x18\x02 \x03(\t2\xbb\x02\n\x10InventoryService\x12T\n\x11\x43heckAvailability\x12\x1e.inventory.AvailabilityRequest\x1a\x1f.inventory.AvailabilityResponse\x12<\n\tLockSeats\x12\x16.inventory.LockRequest\x1a\x17.inventory.LockResponse\x12\x45\n\x0cReleaseSeats\x12\x19.inventory.ReleaseRequest\x1a\x1a.inventory.ReleaseResponse\x12L\n\rAllocateSeats\x12\x1c.inventory.AllocationRequest\x1a\x1d.inventory.AllocationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AVAILABILITYREQUEST']._serialized_start=64
  _globals['_AVAILABILITYREQUEST']._serialized_end=234
  _globals['_AVAILABILITYRESPONSE']._serialized_start=236
  _globals['_AVAILABILITYRESPONSE']._serialized_end=343
  _globals['_LOCKREQUEST']._serialized_start=346
  _globals['_LOCKREQUEST']._serialized_end=527
  _globals['_LOCKRESPONSE']._serialized_start=529
  _globals['_LOCKRESPONSE']._serialized_end=600
  _globals['_RELEASEREQUEST']._serialized_start=602
  _globals['_RELEASEREQUEST']._serialized_end=635
  _globals['_RELEASERESPONSE']._serialized_start=637
  _globals['_RELEASERESPONSE']._serialized_end=671
  _globals['_ALLOCATIONREQUEST']._serialized_start=673
  _globals['_ALLOCATIONREQUEST']._serialized_end=722
  _globals['_ALLOCATIONRESPONSE']._serialized_start=724
  _globals['_ALLOCATIONRESPONSE']._serialized_end=783
  _globals['_INVENTORYSERVICE']._serialized_start=786
  _globals['_INVENTORYSERVICE']._serialized_end=1101
# @@protoc_insertion_point(module_scope)
