from PIL.Image import logger
from typing import List, Dict, Any
from datetime import datetime, timedelta
import logging

# Logic for business solutions (Tasks)
class RouteScorer:
    """
    Applies the 'Core 50' business solutions and persona-based scoring
    to the candidate routes generated by the fast CSA kernel.
    """
    def __init__(self, constraints: Any, graph_accessor: Any = None):
        self.constraints = constraints
        self.graph = graph_accessor
        self.w = constraints.weights
        self.is_conservative_mode = False # [Group 3] Drift fallback flag

    def set_conservative_mode(self, active: bool):
        """Toggles conservative fallback mode for drift mitigation."""
        self.is_conservative_mode = active
        if active:
            logger.warning("🛡️ [SCORER] HEURISTIC FALLBACK ACTIVE: Penalizing complexity to favor reliability.")

    def score_route(self, raw_path: List[Dict]) -> Dict:
        """
        Applies all Tasks (1-50) to a raw path.
        """
        if not raw_path:
            return {"score": 999999}
        
        # Drift-aware penalty multiplier
        p_mult = 2.5 if self.is_conservative_mode else 1.0

        # 1. Base Metrics
        total_duration = (raw_path[-1]["arr_time"] - raw_path[0]["dep_time"]) / 60
        total_cost = self._calculate_cost(raw_path)
        
        # 2. Persona Weights (Task 1)
        score = (self.w.time * total_duration) + (self.w.cost * total_cost)

        # 3. Night-Transfer Penalty (Task 4)
        night_penalty = 0
        transfers = self._extract_transfers(raw_path)
        for tr in transfers:
            # Convert timestamp to hour
            arr_hour = (tr["arr_time"] // 3600) % 24
            
            # Night window: 23:30 (84600s) to 05:00 (18000s)
            if (arr_hour >= 23 or arr_hour < 5):
                night_penalty += (1000 * p_mult) # Scaled by p_mult
        
        score += night_penalty

        # 4. Pantry Car Priority (Task 6)
        pantry_bonus = 0
        if total_duration > 600:
            for seg in raw_path:
                if seg.get("has_pantry", False):
                    pantry_bonus -= 60
        
        score += pantry_bonus

        # 5. Rake Linkage Check (Task 13)
        transfer_count = len(transfers)
        for i in range(len(raw_path) - 1):
            if raw_path[i]["trip_id"] == raw_path[i+1]["trip_id"]:
                transfer_count -= 1 # Not a real transfer
        
        # Task 1: Transfer penalty
        score += (transfer_count * self.w.transfer * p_mult)

        return {
            "path": raw_path,
            "score": score,
            "duration_mins": total_duration,
            "cost": total_cost,
            "transfers": transfer_count,
            "metadata": {
                "night_penalty": night_penalty,
                "pantry_bonus": pantry_bonus,
                "is_rake_link": any(raw_path[i]["trip_id"] == raw_path[i+1]["trip_id"] for i in range(len(raw_path)-1))
            }
        }

    def _calculate_cost(self, path: List[Dict]) -> float:
        # Task 5: Placeholder for complex class-based fare logic
        return sum(seg.get("fare", 500) for seg in path)

    def _extract_transfers(self, path: List[Dict]) -> List[Dict]:
        transfers = []
        for i in range(len(path) - 1):
            if path[i]["arr_stop"] != path[i+1]["dep_stop"] or path[i]["trip_id"] != path[i+1]["trip_id"]:
                transfers.append({
                    "station": path[i]["arr_stop"],
                    "arr_time": path[i]["arr_time"],
                    "dep_time": path[i+1]["dep_time"]
                })
        return transfers
