from sqlalchemy import Column, String, Integer, DateTime, JSON, Float, Boolean, ForeignKey, UniqueConstraint
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from datetime import datetime

Base = declarative_base()

class TrainMaster(Base):
    __tablename__ = "trains_master"
    train_number = Column(String, primary_key=True)
    train_name = Column(String)
    source = Column(String)
    destination = Column(String)
    days_of_run = Column(JSON)  # Stores ["Mon", "Tue"]
    type = Column(String)
    updated_at = Column(DateTime, default=datetime.utcnow)

class TrainStation(Base):
    __tablename__ = "train_stations"
    id = Column(Integer, primary_key=True, autoincrement=True)
    train_number = Column(String, ForeignKey("trains_master.train_number"))
    station_code = Column(String)
    station_name = Column(String)
    sequence = Column(Integer)
    arrival = Column(String)
    departure = Column(String)
    halt_minutes = Column(Integer)
    distance_km = Column(Float)
    day_count = Column(Integer)

    __table_args__ = (UniqueConstraint('train_number', 'sequence', name='uix_train_seq'),)

class LiveStatus(Base):
    __tablename__ = "train_live_status"
    train_number = Column(String, primary_key=True)
    current_station = Column(String)
    status = Column(String)  # On Time, Delayed
    delay_minutes = Column(Integer)
    next_station = Column(String)
    eta_next = Column(String)
    last_updated_ts = Column(DateTime, default=datetime.utcnow)

class SeatAvailability(Base):
    __tablename__ = "seat_availability"
    id = Column(Integer, primary_key=True, autoincrement=True)
    train_number = Column(String)
    class_code = Column(String)  # SL, 3A, 2A
    quota = Column(String)
    availability_status = Column(String)  # AVAILABLE-20, WL10
    fare = Column(Float)
    check_date = Column(DateTime, default=datetime.utcnow)

class ScheduleChangeLog(Base):
    """Records differences detected between a newly extracted schedule and the DB snapshot."""
    __tablename__ = "schedule_change_log"
    id = Column(Integer, primary_key=True, autoincrement=True)
    train_number = Column(String, index=True)
    detected_at = Column(DateTime, default=datetime.utcnow)
    diff = Column(JSON)  # JSON describing changes
    resolved = Column(Boolean, default=False)
    notes = Column(String, nullable=True)


class Alert(Base):
    """Persistent alerts generated by the QA runner or change-detector for dashboard display."""
    __tablename__ = "rma_alerts"
    id = Column(Integer, primary_key=True, autoincrement=True)
    source = Column(String, default="rma_test")
    train_number = Column(String, nullable=True, index=True)
    level = Column(String, default="critical")
    message = Column(String)
    # avoid using attribute name 'metadata' (reserved by SQLAlchemy Declarative API)
    # store alert metadata in column 'meta' to keep attribute name safe
    meta = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    resolved = Column(Boolean, default=False)
    resolved_at = Column(DateTime, nullable=True)
    acknowledged_by = Column(String, nullable=True)


class TrainReliabilityIndex(Base):
    """Stores computed reliability scores for trains (historical records)."""
    __tablename__ = "train_reliability_index"
    id = Column(Integer, primary_key=True, autoincrement=True)
    train_number = Column(String, index=True)
    reliability_score = Column(Float)
    avg_extraction_confidence = Column(Float)
    schedule_drift_score = Column(Float)
    delay_probability = Column(Float)
    computed_at = Column(DateTime, default=datetime.utcnow)
    window_minutes = Column(Integer, default=60)


class TrainLiveUpdate(Base):
    """
    Real-time train status updates from API.
    Stores historical snapshots of train delays, platforms, and positions.
    Used for:
    - Historical dataset for ML training
    - Delay propagation analysis
    - Reliability scoring
    - Anomaly detection
    """
    __tablename__ = "train_live_updates"
    id = Column(Integer, primary_key=True, autoincrement=True)
    train_number = Column(String, index=True)
    station_code = Column(String, index=True)
    station_name = Column(String)
    sequence = Column(Integer)  # Station sequence on route
    distance_km = Column(Float, nullable=True)
    
    # Timing information
    scheduled_arrival = Column(DateTime, nullable=True)
    scheduled_departure = Column(DateTime, nullable=True)
    actual_arrival = Column(DateTime, nullable=True)
    actual_departure = Column(DateTime, nullable=True)
    delay_minutes = Column(Integer, default=0)
    
    # Platform and halt info
    platform = Column(String, nullable=True)
    halt_minutes = Column(Integer, nullable=True)
    
    # Status tracking
    status = Column(String)  # 'On Time', 'Delayed', 'Cancelled', 'Running'
    is_current_station = Column(Boolean, default=False)
    
    # Crawler metadata
    recorded_at = Column(DateTime, default=datetime.utcnow, index=True)
    source = Column(String, default="rappid_api")  # API provider
    
    __table_args__ = (
        UniqueConstraint(
            'train_number', 'station_code', 'recorded_at',
            name='uic_train_realtime_snapshot'
        ),
    )


class RealtimeData(Base):
    """
    Event stream for real-time updates (delays, cancellations, platform changes).
    Processes events and applies them to the routing overlay.
    """
    __tablename__ = "realtime_data"
    id = Column(Integer, primary_key=True, autoincrement=True)
    event_type = Column(String, index=True)  # 'delay', 'cancellation', 'platform_change'
    entity_id = Column(String, index=True)  # trip_id or train_number
    
    # Event payload
    data = Column(JSON)  # {delay_minutes, platform_number, status, etc}
    timestamp = Column(DateTime, default=datetime.utcnow, index=True)
    
    # Processing status
    processed_at = Column(DateTime, nullable=True)
    status = Column(String, default='new')  # 'new', 'processed'


class TrainState(Base):
    """
    Persistent state for trains used by realtime processor.
    Tracks delay propagation and state changes across the route.
    """
    __tablename__ = "train_state"
    id = Column(Integer, primary_key=True, autoincrement=True)
    trip_id = Column(Integer, unique=True, index=True)
    train_number = Column(String, index=True)
    
    # Current state
    current_delay_minutes = Column(Integer, default=0)
    status = Column(String)  # 'on_time', 'delayed', 'cancelled'
    platform_number = Column(String, nullable=True)
    current_station_code = Column(String, nullable=True)
    
    # Metadata
    last_updated = Column(DateTime, default=datetime.utcnow)
    last_update_source = Column(String, nullable=True)  # 'api', 'user', 'system'