from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import Table, TableStyle
import os
import logging

logger = logging.getLogger(__name__)

def generate_branded_ticket(booking_id: str, pnr: str, train_no: str, from_stn: str, to_stn: str, travel_date: str, passengers: list) -> str:
    """
    Task 37: Branded PDF Ticket Generator.
    """
    output_dir = "media/tickets"
    os.makedirs(output_dir, exist_ok=True)
    file_path = f"{output_dir}/ticket_{booking_id}.pdf"
    
    c = canvas.Canvas(file_path, pagesize=letter)
    width, height = letter

    # 1. Header & Branding
    c.setFillColor(colors.HexColor("#3b82f6")) # RouteMaster Blue
    c.rect(0, height - 1.5*inch, width, 1.5*inch, fill=1, stroke=0)
    
    c.setFillColor(colors.white)
    c.setFont("Helvetica-Bold", 24)
    c.drawString(0.5*inch, height - 0.8*inch, "RouteMaster V2")
    c.setFont("Helvetica", 10)
    c.drawString(0.5*inch, height - 1.1*inch, "Autonomous AI Booking Pipeline | Zero-Gateway Escrow")

    # 2. PNR Box
    c.setFillColor(colors.black)
    c.setFont("Helvetica-Bold", 14)
    c.drawString(0.5*inch, height - 2*inch, f"PNR: {pnr}")
    c.setFont("Helvetica", 12)
    c.drawString(width - 2.5*inch, height - 2*inch, f"Date: {travel_date}")

    # 3. Journey Details
    c.line(0.5*inch, height - 2.2*inch, width - 0.5*inch, height - 2.2*inch)
    c.drawString(0.5*inch, height - 2.5*inch, f"Train: {train_no}")
    c.drawString(0.5*inch, height - 2.8*inch, f"Route: {from_stn}  >>>  {to_stn}")

    # 4. Passenger Table
    data = [["Passenger Name", "Age", "Gender", "Status"]]
    for p in passengers:
        data.append([p.get('fullName', 'N/A'), str(p.get('age', '')), p.get('gender', ''), "CNF"])

    t = Table(data, colWidths=[3*inch, 1*inch, 1*inch, 1.5*inch])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#f3f4f6")),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.black),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('GRID', (0, 0), (-1, -1), 1, colors.grey)
    ]))
    
    t.wrapOn(c, width, height)
    t.drawOn(c, 0.5*inch, height - 4.5*inch)

    # 5. Footer & AI Stamp
    c.setFont("Helvetica-Oblique", 8)
    c.setStrokeColor(colors.lightgrey)
    c.drawString(0.5*inch, 0.5*inch, f"Generated by RouteMaster Ghost Worker | Booking ID: {booking_id}")
    
    # AI Verified Stamp
    c.setStrokeColor(colors.green)
    c.setLineWidth(2)
    c.circle(width - 1*inch, 1*inch, 0.4*inch, stroke=1, fill=0)
    c.setFont("Helvetica-Bold", 10)
    c.setFillColor(colors.green)
    c.drawCentredString(width - 1*inch, 1*inch, "AI OK")

    c.save()
    logger.info(f"Ticket generated: {file_path}")
    return file_path
