import logging
import json
from datetime import datetime
from typing import Dict, Any, Optional
from api.sos import _load_event_async as _load_event
from database.session import SessionLocal

logger = logging.getLogger(__name__)

class ReportingService:
    def generate_incident_summary(self, event_id: str) -> Optional[str]:
        """
        Task 37: Generate a structured text/markdown summary of the SOS incident (Sync Wrapper).
        Suitable for RPF handover.
        """
        import asyncio
        event = asyncio.run(self.generate_incident_summary_async(event_id))
        return event

    async def generate_incident_summary_async(self, event_id: str) -> Optional[str]:
        """Async implementation of Task 37."""
        db = SessionLocal()
        try:
            event = await _load_event(event_id, db)
        finally:
            db.close()
            
        if not event:
            return None
            
        summary = []
        summary.append(f"# 🛡️ RouteMaster Incident Report: {event_id}")
        summary.append(f"**Status:** {event.get('status', 'Unknown').upper()}")
        summary.append(f"**Priority:** {event.get('priority', 'Unknown').upper()}")
        summary.append(f"**Category:** {event.get('category', 'Unknown').upper()}")
        summary.append(f"**Triggered At:** {event.get('triggered_at')}")
        
        if event.get('resolved_at'):
            summary.append(f"**Resolved At:** {event.get('resolved_at')}")
            
        summary.append("\n## 👤 Passenger Information")
        summary.append(f"- **Name:** {event.get('name', 'N/A')}")
        summary.append(f"- **Phone:** {event.get('phone', 'N/A')}")
        
        trip = event.get('trip') or {}
        summary.append("\n## 🚆 Trip Context")
        summary.append(f"- **Train Number:** {trip.get('vehicle_number', 'N/A')}")
        summary.append(f"- **Coach:** {trip.get('coach', 'N/A')}")
        
        rail_ctx = event.get('railway_context') or {}
        summary.append(f"- **Current Station (Live):** {rail_ctx.get('current_station', 'N/A')}")
        summary.append(f"- **Platform:** {rail_ctx.get('platform', 'N/A')}")
        
        summary.append("\n## 📍 Location Data")
        summary.append(f"- **Trigger Coordinates:** {event.get('lat')}, {event.get('lng')}")
        summary.append(f"- **Google Maps:** {event.get('google_maps_url')}")
        
        history = event.get('location_history', [])
        if history:
            summary.append("\n### Breadcrumbs (Last 5)")
            for point in history[-5:]:
                summary.append(f"  - {point.get('ts')}: {point.get('lat')}, {point.get('lng')}")
        
        summary.append("\n## 👮 Dispatch Info")
        auth = event.get('nearest_authority') or {}
        summary.append(f"- **Assigned Authority:** {auth.get('name', 'N/A')} ({auth.get('type', 'N/A')})")
        summary.append(f"- **Authority Contact:** {auth.get('contact_number', 'N/A')}")
        summary.append(f"- **Estimated ETA:** {auth.get('eta_mins', 'N/A')} mins")
        
        summary.append("\n## 💬 Communication Log")
        logs = event.get('call_logs', [])
        if logs:
            for log in logs:
                summary.append(f"- [{log.get('timestamp')}] {log.get('type').upper()}: {log.get('content')}")
        else:
            summary.append("*No communication logs available.*")
            
        if event.get('chat_history'):
            summary.append("\n### Chat History")
            for msg in event.get('chat_history', []):
                summary.append(f"- **{msg.get('sender', 'User').capitalize()}:** {msg.get('content')}")

        summary.append("\n---\n*Report generated by RouteMaster V2 Autonomous Safety Pipeline*")
        
        return "\n".join(summary)

reporting_service = ReportingService()
