"""Add seat inventory table

Revision ID: 0e960a4209e7
Revises: ec639a6ec5e6
Create Date: 2026-02-14 15:33:40.378666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e960a4209e7'
down_revision: Union[str, Sequence[str], None] = 'ec639a6ec5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat_inventory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('segment_id', sa.String(length=36), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=False),
    sa.Column('seats_available', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('segment_id', 'travel_date', name='uq_segment_travel_date')
    )
    op.create_index(op.f('ix_seat_inventory_segment_id'), 'seat_inventory', ['segment_id'], unique=False)
    op.create_index(op.f('ix_seat_inventory_travel_date'), 'seat_inventory', ['travel_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seat_inventory_travel_date'), table_name='seat_inventory')
    op.drop_index(op.f('ix_seat_inventory_segment_id'), table_name='seat_inventory')
    op.drop_table('seat_inventory')
    # ### end Alembic commands ###
