"""Overhaul to GTFS data model

Revision ID: 162f7ad310af
Revises: 19d619f63460
Create Date: 2026-02-14 20:06:35.807214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '162f7ad310af'
down_revision: Union[str, Sequence[str], None] = '19d619f63460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agency_agency_id'), 'agency', ['agency_id'], unique=True)
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(length=100), nullable=False),
    sa.Column('monday', sa.Boolean(), nullable=False),
    sa.Column('tuesday', sa.Boolean(), nullable=False),
    sa.Column('wednesday', sa.Boolean(), nullable=False),
    sa.Column('thursday', sa.Boolean(), nullable=False),
    sa.Column('friday', sa.Boolean(), nullable=False),
    sa.Column('saturday', sa.Boolean(), nullable=False),
    sa.Column('sunday', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_service_id'), 'calendar', ['service_id'], unique=True)
    op.create_table('calendar_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exception_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'date', name='uq_service_date')
    )
    op.create_index(op.f('ix_calendar_dates_date'), 'calendar_dates', ['date'], unique=False)
    op.create_index(op.f('ix_calendar_dates_service_id'), 'calendar_dates', ['service_id'], unique=False)
    op.rename_table('routes', 'precalculated_routes')
    op.create_table('stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=False),
    sa.Column('location_type', sa.Integer(), nullable=True),
    sa.Column('parent_station_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_station_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('idx_stops_geom', table_name='stops', if_exists=True)
    op.create_index('idx_stops_geom', 'stops', ['geom'], unique=False, postgresql_using='gist')
    op.drop_index('idx_stops_name_trgm', table_name='stops', if_exists=True)
    op.create_index('idx_stops_name_trgm', 'stops', [sa.text('lower(name) gin_trgm_ops')], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_stops_city'), table_name='stops', if_exists=True)
    op.create_index(op.f('ix_stops_city'), 'stops', ['city'], unique=False)
    op.drop_index(op.f('ix_stops_code'), table_name='stops', if_exists=True)
    op.create_index(op.f('ix_stops_code'), 'stops', ['code'], unique=False)
    op.drop_index(op.f('ix_stops_name'), table_name='stops', if_exists=True)
    op.create_index(op.f('ix_stops_name'), 'stops', ['name'], unique=False)
    op.drop_index(op.f('ix_stops_stop_id'), table_name='stops', if_exists=True)
    op.create_index(op.f('ix_stops_stop_id'), 'stops', ['stop_id'], unique=True)
    op.create_table('gtfs_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.String(length=100), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('long_name', sa.String(length=255), nullable=False),
    sa.Column('route_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agency_id'], ['agency.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gtfs_routes_agency_id'), 'gtfs_routes', ['agency_id'], unique=False)
    op.create_index(op.f('ix_gtfs_routes_route_id'), 'gtfs_routes', ['route_id'], unique=True)
    op.create_index(op.f('ix_gtfs_routes_route_type'), 'gtfs_routes', ['route_type'], unique=False)
    op.create_table('transfers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_stop_id', sa.Integer(), nullable=False),
    sa.Column('to_stop_id', sa.Integer(), nullable=False),
    sa.Column('transfer_type', sa.Integer(), nullable=False),
    sa.Column('min_transfer_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['from_stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['to_stop_id'], ['stops.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.String(length=255), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('headsign', sa.String(length=255), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['gtfs_routes.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['calendar.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trips_direction_id'), 'trips', ['direction_id'], unique=False)
    op.create_index(op.f('ix_trips_route_id'), 'trips', ['route_id'], unique=False)
    op.create_index(op.f('ix_trips_service_id'), 'trips', ['service_id'], unique=False)
    op.create_index(op.f('ix_trips_trip_id'), 'trips', ['trip_id'], unique=True)
    op.create_table('stop_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.Integer(), nullable=False),
    sa.Column('arrival_time', sa.Time(), nullable=False),
    sa.Column('departure_time', sa.Time(), nullable=False),
    sa.Column('stop_sequence', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stop_id'], ['stops.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'stop_sequence', name='uq_trip_stop_sequence')
    )
    op.create_index('idx_stop_times_stop_id', 'stop_times', ['stop_id'], unique=False)
    op.create_index('idx_stop_times_trip_id', 'stop_times', ['trip_id'], unique=False)




    op.add_column('bookings', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.alter_column('bookings', 'travel_date',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Date(),
               existing_nullable=False,
               postgresql_using='travel_date::date')
    op.alter_column('bookings', 'route_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('uq_user_route_travel_date', 'bookings', type_='unique')
    op.drop_constraint('bookings_route_id_fkey', 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'bookings', 'precalculated_routes', ['route_id'], ['id'])
    op.drop_constraint('commission_tracking_tracking_id_key', 'commission_tracking', type_='unique')
    op.drop_index('idx_commission_partner_status', table_name='commission_tracking')
    op.drop_index('idx_commission_tracking_id', table_name='commission_tracking')
    op.drop_index('idx_commission_user_redirected', table_name='commission_tracking')
    op.create_index(op.f('ix_commission_tracking_tracking_id'), 'commission_tracking', ['tracking_id'], unique=True)
    op.drop_column('commission_tracking', 'ip_address')
    op.drop_column('commission_tracking', 'passengers')
    op.drop_column('commission_tracking', 'commission_amount')
    op.drop_column('commission_tracking', 'cache_key')
    op.drop_column('commission_tracking', 'session_id')
    op.drop_column('commission_tracking', 'route_type')
    op.drop_column('commission_tracking', 'tracking_metadata')
    op.drop_column('commission_tracking', 'converted_at')
    op.drop_column('commission_tracking', 'user_agent')
    op.add_column('disruptions', sa.Column('created_by_id', sa.String(length=36), nullable=True))
    op.add_column('disruptions', sa.Column('gtfs_route_id', sa.Integer(), nullable=True))
    op.add_column('disruptions', sa.Column('trip_id', sa.Integer(), nullable=True))
    op.add_column('disruptions', sa.Column('stop_id', sa.Integer(), nullable=True))
    op.drop_index('idx_disruption_route_date', table_name='disruptions')
    op.drop_index('idx_disruption_status', table_name='disruptions')
    op.drop_index('ix_disruptions_route_id', table_name='disruptions')
    op.create_index(op.f('ix_disruptions_gtfs_route_id'), 'disruptions', ['gtfs_route_id'], unique=False)
    op.create_index(op.f('ix_disruptions_stop_id'), 'disruptions', ['stop_id'], unique=False)
    op.create_index(op.f('ix_disruptions_trip_id'), 'disruptions', ['trip_id'], unique=False)
    op.drop_constraint('disruptions_created_by_fkey', 'disruptions', type_='foreignkey')
    op.create_foreign_key(None, 'disruptions', 'stops', ['stop_id'], ['id'])
    op.create_foreign_key(None, 'disruptions', 'users', ['created_by_id'], ['id'])
    op.create_foreign_key(None, 'disruptions', 'trips', ['trip_id'], ['id'])
    op.create_foreign_key(None, 'disruptions', 'gtfs_routes', ['gtfs_route_id'], ['id'])
    op.drop_column('disruptions', 'created_by')
    op.drop_column('disruptions', 'disruption_date')
    op.drop_column('disruptions', 'route_id')
    op.drop_column('disruptions', 'updated_at')
    op.drop_column('disruptions', 'severity')
    op.create_unique_constraint('uq_user_booking_review', 'reviews', ['user_id', 'booking_id'])
    op.add_column('seat_inventory', sa.Column('stop_time_id', sa.Integer(), nullable=False))
    op.drop_index('ix_seat_inventory_segment_id', table_name='seat_inventory')
    op.drop_constraint('uq_segment_travel_date', 'seat_inventory', type_='unique')
    op.create_index(op.f('ix_seat_inventory_stop_time_id'), 'seat_inventory', ['stop_time_id'], unique=False)
    op.drop_constraint('seat_inventory_segment_id_fkey', 'seat_inventory', type_='foreignkey')
    op.create_foreign_key(None, 'seat_inventory', 'stop_times', ['stop_time_id'], ['id'])
    op.drop_column('seat_inventory', 'segment_id')
    op.alter_column('unlocked_routes', 'route_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_constraint('unlocked_routes_route_id_fkey', 'unlocked_routes', type_='foreignkey')
    op.create_foreign_key(None, 'unlocked_routes', 'precalculated_routes', ['route_id'], ['id'])

    # Now, drop the old tables after all dependencies are removed
    op.drop_table('segments')
    op.drop_table('vehicles')
    op.drop_table('stations_master')
    op.drop_table('stations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
