"""Add commission tracking table for secure attribution

Revision ID: 16871f90bb4d
Revises: 924ba912e096
Create Date: 2026-02-14 18:39:39.678120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import geoalchemy2

# revision identifiers, used by Alembic.
revision: str = '16871f90bb4d'
down_revision: Union[str, Sequence[str], None] = '924ba912e096'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commission_tracking',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('route_type', sa.String(length=50), nullable=False),
    sa.Column('travel_date', sa.Date(), nullable=True),
    sa.Column('passengers', sa.Integer(), nullable=True),
    sa.Column('partner', sa.String(length=100), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('tracking_id', sa.String(length=64), nullable=False),
    sa.Column('redirect_url', sa.Text(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('redirected_at', sa.DateTime(), nullable=True),
    sa.Column('converted_at', sa.DateTime(), nullable=True),
    sa.Column('commission_amount', sa.Float(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('tracking_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tracking_id')
    )
    op.create_index('idx_commission_partner_status', 'commission_tracking', ['partner', 'status'], unique=False)
    op.create_index('idx_commission_tracking_id', 'commission_tracking', ['tracking_id'], unique=True)
    op.create_index('idx_commission_user_redirected', 'commission_tracking', ['user_id', 'redirected_at'], unique=False)
    op.create_index(op.f('ix_commission_tracking_partner'), 'commission_tracking', ['partner'], unique=False)
    op.create_index(op.f('ix_commission_tracking_redirected_at'), 'commission_tracking', ['redirected_at'], unique=False)
    op.create_index(op.f('ix_commission_tracking_status'), 'commission_tracking', ['status'], unique=False)
    op.create_index(op.f('ix_commission_tracking_user_id'), 'commission_tracking', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_commission_tracking_user_id'), table_name='commission_tracking')
    op.drop_index(op.f('ix_commission_tracking_status'), table_name='commission_tracking')
    op.drop_index(op.f('ix_commission_tracking_redirected_at'), table_name='commission_tracking')
    op.drop_index(op.f('ix_commission_tracking_partner'), table_name='commission_tracking')
    op.drop_index('idx_commission_user_redirected', table_name='commission_tracking')
    op.drop_index('idx_commission_tracking_id', table_name='commission_tracking')
    op.drop_index('idx_commission_partner_status', table_name='commission_tracking')
    op.drop_table('commission_tracking')
    # ### end Alembic commands ###
    sa.Column('statefp', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('zcta5ce', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
