"""add_disruptions_table_only

Revision ID: 19d619f63460
Revises: 16871f90bb4d
Create Date: 2026-02-14 19:28:21.172407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19d619f63460'
down_revision: Union[str, Sequence[str], None] = '16871f90bb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disruptions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('route_id', sa.String(length=36), nullable=False),
    sa.Column('disruption_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disruption_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_disruption_route_date', 'disruptions', ['route_id', 'disruption_date'], unique=False)
    op.create_index('idx_disruption_status', 'disruptions', ['status'], unique=False)
    op.create_index(op.f('ix_disruptions_route_id'), 'disruptions', ['route_id'], unique=False)
    op.create_index(op.f('ix_disruptions_status'), 'disruptions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_disruptions_status'), table_name='disruptions')
    op.drop_index(op.f('ix_disruptions_route_id'), table_name='disruptions')
    op.drop_index('idx_disruption_status', table_name='disruptions')
    op.drop_index('idx_disruption_route_date', table_name='disruptions')
    op.drop_table('disruptions')
    # ### end Alembic commands ###
