"""Initial database setup

Revision ID: 7873edeccc66
Revises: c68aad02c91b
Create Date: 2026-02-14 06:12:27.429807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7873edeccc66'
down_revision: Union[str, Sequence[str], None] = 'c68aad02c91b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - adjusted to drop dependents first ###
    # drop child tables first (reviews -> payments -> unlocked_routes -> bookings -> users)
    op.drop_index(op.f('ix_reviews_booking_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_id'), table_name='reviews')
    op.drop_table('reviews')

    op.drop_index(op.f('ix_unlocked_routes_payment_id'), table_name='unlocked_routes')
    op.drop_index(op.f('ix_unlocked_routes_route_id'), table_name='unlocked_routes')
    op.drop_index(op.f('ix_unlocked_routes_user_id'), table_name='unlocked_routes')
    op.drop_table('unlocked_routes')

    op.drop_index(op.f('ix_payments_booking_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_order_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_table('payments')

    # now safe to drop bookings (parents removed)
    op.drop_index(op.f('ix_bookings_created_at'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_user_id'), table_name='bookings')
    op.drop_table('bookings')

    # users can be removed after their dependents
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # routes (after unlocked_routes/bookings removed)
    op.drop_index(op.f('ix_routes_created_at'), table_name='routes')
    op.drop_index(op.f('ix_routes_destination'), table_name='routes')
    op.drop_index(op.f('ix_routes_source'), table_name='routes')
    op.drop_table('routes')

    # segments must be removed before stations/vehicles
    op.drop_index(op.f('ix_segments_dest_station_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_source_station_id'), table_name='segments')
    op.drop_index(op.f('ix_segments_vehicle_id'), table_name='segments')
    op.drop_table('segments')

    # vehicles (after segments)
    op.drop_table('vehicles')

    # stations & related spatial tables
    op.drop_index(op.f('idx_stations_geom'), table_name='stations', postgresql_using='gist')
    op.drop_index(op.f('ix_stations_city'), table_name='stations')
    op.drop_index(op.f('ix_stations_name'), table_name='stations')
    op.drop_table('stations')

    op.drop_index(op.f('ix_stations_master_city'), table_name='stations_master')
    op.drop_index(op.f('ix_stations_master_station_name'), table_name='stations_master')
    op.drop_table('stations_master')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('rating', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('review_rating_check')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('reviews_booking_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('reviews_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_pkey'))
    )
    op.create_index(op.f('ix_reviews_user_id'), 'reviews', ['user_id'], unique=False)
    op.create_index(op.f('ix_reviews_booking_id'), 'reviews', ['booking_id'], unique=True)
    op.create_table('stations',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('geom', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('stations_pkey'))
    )
    op.create_index(op.f('ix_stations_name'), 'stations', ['name'], unique=False)
    op.create_index(op.f('ix_stations_city'), 'stations', ['city'], unique=False)
    op.create_index(op.f('idx_stations_geom'), 'stations', ['geom'], unique=False, postgresql_using='gist')
    op.create_table('stations_master',
    sa.Column('station_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('station_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('state', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('is_junction', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('geo_hash', sa.VARCHAR(length=12), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('station_code', name=op.f('stations_master_pkey'))
    )
    op.create_index(op.f('ix_stations_master_station_name'), 'stations_master', ['station_name'], unique=False)
    op.create_index(op.f('ix_stations_master_city'), 'stations_master', ['city'], unique=False)

    op.create_table('routes',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('segments', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('total_duration', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('total_cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('budget_category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('num_transfers', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('routes_pkey'))
    )
    op.create_index(op.f('ix_routes_source'), 'routes', ['source'], unique=False)
    op.create_index(op.f('ix_routes_destination'), 'routes', ['destination'], unique=False)
    op.create_index(op.f('ix_routes_created_at'), 'routes', ['created_at'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('source_station_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('dest_station_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('vehicle_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('transport_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('departure_time', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('arrival_time', sa.VARCHAR(length=8), autoincrement=False, nullable=False),
    sa.Column('duration_minutes', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distance_km', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('arrival_day_offset', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cost', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('operating_days', sa.VARCHAR(length=7), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dest_station_id'], ['stations.id'], name=op.f('segments_dest_station_id_fkey')),
    sa.ForeignKeyConstraint(['source_station_id'], ['stations.id'], name=op.f('segments_source_station_id_fkey')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('segments_vehicle_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('segments_pkey'))
    )
    op.create_index(op.f('ix_segments_vehicle_id'), 'segments', ['vehicle_id'], unique=False)
    op.create_index(op.f('ix_segments_source_station_id'), 'segments', ['source_station_id'], unique=False)
    op.create_index(op.f('ix_segments_dest_station_id'), 'segments', ['dest_station_id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('vehicle_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('operator', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('capacity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("type::text = ANY (ARRAY['train'::character varying, 'bus'::character varying, 'flight'::character varying]::text[])", name=op.f('vehicle_type_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('vehicles_pkey'))
    )
    op.create_table('payments',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('razorpay_order_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('razorpay_payment_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('payments_booking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_razorpay_order_id'), 'payments', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_payments_booking_id'), 'payments', ['booking_id'], unique=False)
    op.create_table('unlocked_routes',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('unlocked_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('unlocked_routes_payment_id_fkey')),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('unlocked_routes_route_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('unlocked_routes_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('unlocked_routes_pkey'))
    )
    op.create_index(op.f('ix_unlocked_routes_user_id'), 'unlocked_routes', ['user_id'], unique=False)
    op.create_index(op.f('ix_unlocked_routes_route_id'), 'unlocked_routes', ['route_id'], unique=False)
    op.create_index(op.f('ix_unlocked_routes_payment_id'), 'unlocked_routes', ['payment_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('bookings',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('route_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('travel_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('payment_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('amount_paid', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('booking_details', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], name=op.f('bookings_route_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('bookings_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bookings_pkey'))
    )
    op.create_index(op.f('ix_bookings_user_id'), 'bookings', ['user_id'], unique=False)
    op.create_index(op.f('ix_bookings_created_at'), 'bookings', ['created_at'], unique=False)
    # ### end Alembic commands ###
