"""Add PostGIS and trgm indexes for location-based search

Revision ID: 924ba912e096
Revises: e5887621aa5b
Create Date: 2026-02-14 18:34:00.492624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '924ba912e096'
down_revision: Union[str, Sequence[str], None] = 'e5887621aa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')
    op.execute('CREATE INDEX IF NOT EXISTS idx_stations_city_trgm ON stations USING gin (lower(city) gin_trgm_ops);')
    op.execute('CREATE INDEX IF NOT EXISTS idx_stations_name_trgm ON stations USING gin (lower(name) gin_trgm_ops);')
    op.execute('CREATE INDEX IF NOT EXISTS idx_stations_master_city_trgm ON stations_master USING gin (lower(city) gin_trgm_ops);')
    op.execute('CREATE INDEX IF NOT EXISTS idx_stations_master_name_trgm ON stations_master USING gin (lower(station_name) gin_trgm_ops);')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP INDEX IF EXISTS idx_stations_master_name_trgm;')
    op.execute('DROP INDEX IF EXISTS idx_stations_master_city_trgm;')
    op.execute('DROP INDEX IF EXISTS idx_stations_name_trgm;')
    op.execute('DROP INDEX IF EXISTS idx_stations_city_trgm;')
    # ### end Alembic commands ###
