"""Add last_reconciled_at to seat_inventory

Revision ID: e5887621aa5b
Revises: 0e960a4209e7
Create Date: 2026-02-14 15:45:13.713556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5887621aa5b'
down_revision: Union[str, Sequence[str], None] = '0e960a4209e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat_inventory', sa.Column('last_reconciled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat_inventory', 'last_reconciled_at')
    # ### end Alembic commands ###
