"""Add unique constraint to bookings

Revision ID: ec639a6ec5e6
Revises: 41af9fd39336
Create Date: 2026-02-14 15:28:54.471205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec639a6ec5e6'
down_revision: Union[str, Sequence[str], None] = '41af9fd39336'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_route_travel_date', 'bookings', ['user_id', 'route_id', 'travel_date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_route_travel_date', 'bookings', type_='unique')
    # ### end Alembic commands ###
