/**
 * Route cache loaded from generated route_cache.json.
 * Generated by: python backend/scripts/generate_route_cache.py (with backend running).
 * Keys are ORIG_DEST_YYYY-MM-DD so dates matter (trains run on specific days).
 */
import type { BackendRoutesResponse } from "@/services/railwayBackApi";

export interface RouteCacheMeta {
  generatedAt: string | null;
  pairs: string[];
  dates: string[];
  description?: string;
}

export interface RouteCacheFile {
  meta: RouteCacheMeta;
  routes: Record<string, BackendRoutesResponse>;
}

// Load generated cache (real data from backend /routes). Empty until generate_route_cache.py is run.
import routeCacheJson from "./route_cache.json";

const routeCache = routeCacheJson as RouteCacheFile;

function cacheKey(originCode: string, destCode: string, dateStr: string): string {
  const o = String(originCode ?? "").trim().toUpperCase();
  const d = String(destCode ?? "").trim().toUpperCase();
  const date = normalizeDate(dateStr);
  if (!o || !d || !date) return "";
  return `${o}_${d}_${date}`;
}

/** Normalize date to YYYY-MM-DD for cache lookup. */
export function normalizeDate(dateStr: string | undefined): string {
  if (!dateStr || typeof dateStr !== "string") return "";
  const s = dateStr.trim();
  if (!s) return "";
  // Already YYYY-MM-DD
  if (/^\d{4}-\d{2}-\d{2}$/.test(s)) return s;
  // DD/MM/YYYY or DD-MM-YYYY
  const m = s.match(/^(\d{1,2})[/-](\d{1,2})[/-](\d{4})$/);
  if (m) {
    const [, day, month, year] = m;
    return `${year}-${month.padStart(2, "0")}-${day.padStart(2, "0")}`;
  }
  return "";
}

/**
 * Get cached backend response for (origin, dest, date), if available.
 * Returns the same shape as GET /routes so frontend can use mapBackendRoutesToRoutes.
 * Date must match a generated date (trains run on specific days).
 */
export function getCachedRoutes(
  originCode: string,
  destCode: string,
  dateStr: string
): BackendRoutesResponse | null {
  const key = cacheKey(originCode, destCode, dateStr);
  if (!key) return null;
  const entry = routeCache.routes?.[key] ?? null;
  return entry ?? null;
}

/** Pairs and dates that were used to generate the cache (for UI hint). */
export const CACHED_PAIRS = [
  { origin: "NDLS", originName: "New Delhi", dest: "BCT", destName: "Mumbai Central", description: "Delhi to Mumbai - India's busiest route" },
  { origin: "HWH", originName: "Howrah Junction", dest: "NDLS", destName: "New Delhi", description: "Kolkata to Delhi - Eastern corridor" },
  { origin: "MAS", originName: "Chennai Central", dest: "SBC", destName: "Bangalore City", description: "Chennai to Bangalore - South India express" },
  { origin: "PUNE", originName: "Pune Junction", dest: "NDLS", destName: "New Delhi", description: "Pune to Delhi - Western route" },
  { origin: "LKO", originName: "Lucknow Junction", dest: "BCT", destName: "Mumbai Central", description: "Lucknow to Mumbai - Central corridor" },
];

export function getCacheMeta(): RouteCacheMeta {
  return routeCache.meta ?? { generatedAt: null, pairs: [], dates: [] };
}
