# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: booking.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'booking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbooking.proto\x12\x07\x62ooking\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf9\x01\n\x0e\x42ookingRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x10\n\x08train_id\x18\x02 \x01(\t\x12\x14\n\x0c\x66rom_stop_id\x18\x03 \x01(\t\x12\x12\n\nto_stop_id\x18\x04 \x01(\t\x12/\n\x0btravel_date\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nquota_type\x18\x06 \x01(\t\x12\x12\n\nclass_type\x18\x07 \x01(\t\x12&\n\npassengers\x18\x08 \x03(\x0b\x32\x12.booking.Passenger\x12\x19\n\x11payment_method_id\x18\t \x01(\t\"P\n\tPassenger\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x18\n\x10\x62\x65rth_preference\x18\x04 \x01(\t\"s\n\x0f\x42ookingResponse\x12\x0b\n\x03pnr\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0ctotal_amount\x18\x03 \x01(\x01\x12\x16\n\x0etransaction_id\x18\x04 \x01(\t\x12\x15\n\rerror_message\x18\x05 \x01(\t\"\x1c\n\rStatusRequest\x12\x0b\n\x03pnr\x18\x01 \x01(\t\"u\n\x0eStatusResponse\x12\x0b\n\x03pnr\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x14\n\x0cseat_numbers\x18\x03 \x03(\t\x12\x30\n\x0c\x62ooking_time\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\",\n\rCancelRequest\x12\x0b\n\x03pnr\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"Q\n\x0e\x43\x61ncelResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rrefund_amount\x18\x02 \x01(\x01\x12\x17\n\x0f\x63\x61ncellation_id\x18\x03 \x01(\t2\xdd\x01\n\x0e\x42ookingService\x12\x44\n\x0fInitiateBooking\x12\x17.booking.BookingRequest\x1a\x18.booking.BookingResponse\x12\x43\n\x10GetBookingStatus\x12\x16.booking.StatusRequest\x1a\x17.booking.StatusResponse\x12@\n\rCancelBooking\x12\x16.booking.CancelRequest\x1a\x17.booking.CancelResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'booking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BOOKINGREQUEST']._serialized_start=60
  _globals['_BOOKINGREQUEST']._serialized_end=309
  _globals['_PASSENGER']._serialized_start=311
  _globals['_PASSENGER']._serialized_end=391
  _globals['_BOOKINGRESPONSE']._serialized_start=393
  _globals['_BOOKINGRESPONSE']._serialized_end=508
  _globals['_STATUSREQUEST']._serialized_start=510
  _globals['_STATUSREQUEST']._serialized_end=538
  _globals['_STATUSRESPONSE']._serialized_start=540
  _globals['_STATUSRESPONSE']._serialized_end=657
  _globals['_CANCELREQUEST']._serialized_start=659
  _globals['_CANCELREQUEST']._serialized_end=703
  _globals['_CANCELRESPONSE']._serialized_start=705
  _globals['_CANCELRESPONSE']._serialized_end=786
  _globals['_BOOKINGSERVICE']._serialized_start=789
  _globals['_BOOKINGSERVICE']._serialized_end=1010
# @@protoc_insertion_point(module_scope)
