"""
Booking API endpoints
POST /api/v1/bookings/create - Create booking
POST /api/v1/bookings/{id}/confirm-payment - Confirm payment
GET /api/v1/bookings/{id} - Get booking details
GET /api/v1/bookings/my - Get user bookings
POST /api/v1/bookings/{id}/cancel - Cancel booking
POST /api/v1/bookings/{id}/review - Add review
"""

from datetime import datetime
from decimal import Decimal
from typing import Optional
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, Query
from sqlalchemy.orm import Session
from pydantic import BaseModel, Field

from database.infrastructure.session import get_db
from database.models.booking_models import Booking, Payment
from services.booking_service import BookingService, PaymentService, RefundService
from core.auth import get_current_user

router = APIRouter(prefix="/api/v1/bookings", tags=["bookings"])


# ============ Request/Response Models ============

class BookingCreateRequest(BaseModel):
    """Request to create a booking"""
    train_number: str = Field(..., min_length=1)
    journey_date: str = Field(..., regex=r"^\d{4}-\d{2}-\d{2}$")
    source_station: str = Field(..., min_length=3)
    destination_station: str = Field(..., min_length=3)
    class_type: str = Field(..., regex=r"^(1A|2A|3A|SL)$")
    passenger_name: str = Field(..., min_length=2)
    passenger_email: Optional[str] = None
    passenger_phone: str = Field(..., regex=r"^\+?91\d{10}$")
    passenger_gender: str = Field(..., regex=r"^(M|F|Other)$")
    passenger_dob: Optional[str] = None
    base_fare: float
    taxes: float = 0
    service_fee: float = 50


class BookingResponse(BaseModel):
    """Booking response with payment details"""
    booking_id: str
    status: str
    razorpay_order_id: str
    razorpay_amount: int
    razorpay_currency: str
    razorpay_key_id: str
    total_fare: float
    created_at: str


class PaymentConfirmRequest(BaseModel):
    """Payment confirmation from Razorpay"""
    razorpay_order_id: str
    razorpay_payment_id: str
    razorpay_signature: str


class BookingDetailResponse(BaseModel):
    """Detailed booking information"""
    id: str
    train_number: str
    journey_date: str
    source_station: str
    destination_station: str
    class_type: str
    passenger_name: str
    passenger_email: Optional[str]
    passenger_phone: str
    status: str
    pnr: Optional[str]
    ticket_number: Optional[str]
    total_fare: float
    created_at: str


class CancelBookingRequest(BaseModel):
    """Request to cancel booking"""
    reason: str = Field(..., min_length=5)


class ReviewRequest(BaseModel):
    """Post-journey review"""
    overall_rating: int = Field(..., ge=1, le=5)
    review_text: Optional[str] = None
    cleanliness_rating: Optional[int] = Field(None, ge=1, le=5)
    comfort_rating: Optional[int] = Field(None, ge=1, le=5)
    staff_rating: Optional[int] = Field(None, ge=1, le=5)
    food_rating: Optional[int] = Field(None, ge=1, le=5)


# ============ Endpoints ============

@router.post("/create", response_model=BookingResponse)
async def create_booking(
    request: BookingCreateRequest,
    current_user = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Create a new booking - returns Razorpay order details"""
    try:
        booking = BookingService.create_booking(
            db=db,
            user_id=UUID(current_user["user_id"]),
            train_number=request.train_number,
            journey_date=request.journey_date,
            source_station=request.source_station,
            destination_station=request.destination_station,
            class_type=request.class_type,
            passenger_name=request.passenger_name,
            passenger_email=request.passenger_email,
            passenger_phone=request.passenger_phone,
            passenger_gender=request.passenger_gender,
            passenger_dob=request.passenger_dob,
            base_fare=Decimal(str(request.base_fare)),
            taxes=Decimal(str(request.taxes)),
            service_fee=Decimal(str(request.service_fee)),
        )
        
        # Create payment record
        payment = PaymentService.create_payment_record(
            db=db,
            booking_id=booking.id,
            amount=booking.total_fare,
            razorpay_order_id="order_placeholder",  # Will be generated by Razorpay
        )
        
        # TODO: Call Razorpay API to create actual order
        import os
        razorpay_key_id = os.getenv("RAZORPAY_KEY_ID", "")
        
        return BookingResponse(
            booking_id=str(booking.id),
            status=booking.status,
            razorpay_order_id=payment.razorpay_order_id,
            razorpay_amount=int(booking.total_fare * 100),  # Convert to paise
            razorpay_currency="INR",
            razorpay_key_id=razorpay_key_id,
            total_fare=float(booking.total_fare),
            created_at=booking.created_at.isoformat(),
        )
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.post("/{booking_id}/confirm-payment")
async def confirm_payment(
    booking_id: str,
    request: PaymentConfirmRequest,
    current_user = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Confirm payment after Razorpay success"""
    try:
        booking = BookingService.get_booking(db, UUID(booking_id))
        if not booking:
            raise HTTPException(status_code=404, detail="Booking not found")
        
        if str(booking.user_id) != current_user["user_id"]:
            raise HTTPException(status_code=403, detail="Unauthorized")
        
        payment = PaymentService.get_payment_by_booking(db, booking.id)
        if not payment:
            raise HTTPException(status_code=404, detail="Payment not found")
        
        # Verify Razorpay signature (TODO: implement)
        # For now, just update
        
        payment = PaymentService.confirm_payment(
            db=db,
            payment_id=payment.id,
            razorpay_payment_id=request.razorpay_payment_id,
            razorpay_signature=request.razorpay_signature,
        )
        
        return {
            "booking_id": str(booking.id),
            "status": "PAYMENT_CONFIRMED",
            "message": "Payment confirmed. Waiting for IRCTC ticket issuance.",
        }
    except Exception as e:
        raise HTTPException(status_code=400, detail=str(e))


@router.get("/{booking_id}", response_model=BookingDetailResponse)
async def get_booking(
    booking_id: str,
    current_user = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Get booking details"""
    booking = BookingService.get_booking(db, UUID(booking_id))
    if not booking:
        raise HTTPException(status_code=404, detail="Booking not found")
    
    if str(booking.user_id) != current_user["user_id"]:
        raise HTTPException(status_code=403, detail="Unauthorized")
    
    return BookingDetailResponse(
        id=str(booking.id),
        train_number=booking.train_number,
        journey_date=str(booking.journey_date),
        source_station=booking.source_station,
        destination_station=booking.destination_station,
        class_type=booking.class_type,
        passenger_name=booking.passenger_name,
        passenger_email=booking.passenger_email,
        passenger_phone=booking.passenger_phone,
        status=booking.status,
        pnr=booking.pnr,
        ticket_number=booking.ticket_number,
        total_fare=float(booking.total_fare),
        created_at=booking.created_at.isoformat(),
    )


@router.get("/my", )
async def get_user_bookings(
    status: Optional[str] = Query(None),
    limit: int = Query(10, ge=1, le=100),
    offset: int = Query(0, ge=0),
    current_user = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Get user's bookings"""
    bookings, total = BookingService.get_user_bookings(
        db=db,
        user_id=UUID(current_user["user_id"]),
        status=status,
        limit=limit,
        offset=offset,
    )
    
    return {
        "bookings": [
            {
                "id": str(b.id),
                "train_number": b.train_number,
                "journey_date": str(b.journey_date),
                "source_station": b.source_station,
                "destination_station": b.destination_station,
                "status": b.status,
                "pnr": b.pnr,
                "total_fare": float(b.total_fare),
                "created_at": b.created_at.isoformat(),
            }
            for b in bookings
        ],
        "total": total,
        "limit": limit,
        "offset": offset,
    }


@router.post("/{booking_id}/cancel")
async def cancel_booking(
    booking_id: str,
    request: CancelBookingRequest,
    current_user = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Cancel a booking"""
    booking = BookingService.get_booking(db, UUID(booking_id))
    if not booking:
        raise HTTPException(status_code=404, detail="Booking not found")
    
    if str(booking.user_id) != current_user["user_id"]:
        raise HTTPException(status_code=403, detail="Unauthorized")
    
    booking, refund = BookingService.cancel_booking(
        db=db,
        booking_id=booking.id,
        reason=request.reason,
    )
    
    return {
        "booking_id": str(booking.id),
        "status": booking.status,
        "refund_amount": float(booking.refund_amount) if booking.refund_amount else 0,
        "message": "Booking cancelled. Refund will be processed within 3-5 business days.",
    }


@router.post("/{booking_id}/review")
async def add_review(
    booking_id: str,
    request: ReviewRequest,
    current_user = Depends(get_current_user),
    db: Session = Depends(get_db),
):
    """Add post-journey review"""
    booking = BookingService.get_booking(db, UUID(booking_id))
    if not booking:
        raise HTTPException(status_code=404, detail="Booking not found")
    
    if str(booking.user_id) != current_user["user_id"]:
        raise HTTPException(status_code=403, detail="Unauthorized")
    
    # TODO: Implement review creation
    return {
        "booking_id": str(booking.id),
        "message": "Review submitted",
    }
