import hmac
import hashlib
import requests
import json
import os
import jwt
from datetime import datetime, timedelta

# Configuration
API_BASE = "http://127.0.0.1:8000/api"
SECRET_KEY = "EliteAuthMaster2026!" # Found in .env earlier
ALGORITHM = "HS256"
RAZORPAY_KEY_SECRET = "zrM8c2rvPzoBCut2ah7z7TcC"

def get_token():
    payload = {
        "sub": "user_hardened",
        "exp": datetime.utcnow() + timedelta(hours=1)
    }
    return jwt.encode(payload, SECRET_KEY, algorithm=ALGORITHM)

def run_test_transaction():
    headers = {
        "X-Dev-Bypass": "TRUE",
        "Authorization": "Bearer dev-bypass",
        "Content-Type": "application/json"
    }

    print("--- Step 1: Creating Razorpay Order ---")
    order_payload = {
        "amount": 50000, # ₹500.00
        "currency": "INR",
        "receipt": "test_txn_001",
        "notes": {"description": "End-to-End Test Transaction"}
    }
    
    res = requests.post(f"{API_BASE}/razorpay/create-order", json=order_payload, headers=headers)
    if res.status_code != 200:
        print(f"Failed to create order: {res.text}")
        return
    
    order_data = res.json()
    order_id = order_data["order_id"]
    print(f"Order Created: {order_id}")

    print("\n--- Step 2: Simulating Razorpay Modal Success ---")
    # Simulate a payment ID generated by Razorpay
    payment_id = "pay_test_12345"
    
    # Generate the signature manually (as Razorpay would)
    msg = f"{order_id}|{payment_id}"
    signature = hmac.new(
        RAZORPAY_KEY_SECRET.encode(),
        msg.encode(),
        hashlib.sha256
    ).hexdigest()
    print(f"Generated Mock Signature: {signature}")

    print("\n--- Step 3: Verifying Signature on Backend ---")
    verify_payload = {
        "payment_id": "draft_booking_123", # Our internal reference
        "razorpay_order_id": order_id,
        "razorpay_payment_id": payment_id,
        "razorpay_signature": signature
    }
    
    v_res = requests.post(f"{API_BASE}/razorpay/verify-payment", json=verify_payload, headers=headers)
    print(f"Verification Response: {v_res.status_code}")
    print(f"Body: {v_res.text}")

    if v_res.status_code == 200 and v_res.json().get("success"):
        print("\n✅ TEST TRANSACTION SUCCESSFUL")
    else:
        print("\n❌ TEST TRANSACTION FAILED")

if __name__ == "__main__":
    run_test_transaction()
