"""
Shadow Guide Agent
====================
Patent Innovation #4: Stateful autonomous journey companion.

The Shadow Guide is a persistent agent that attaches to a user from the moment
they search for a journey until they arrive at their destination. It acts as
an intelligent travel companion that:

PRE-JOURNEY:
    - Monitors seat availability and alerts if status changes
    - Suggests optimal departure times based on crowd predictions
    - Pre-books station amenities (lounge, food) at wait stations
    - Sends weather alerts and packing suggestions

DURING JOURNEY:
    - Real-time delay monitoring with proactive alternatives
    - Emergency Intercept: Auto-finds bus/cab if train is stranded
    - Food ordering at upcoming stations
    - Safety monitoring (night travel, remote stops)
    - Platform change alerts

POST-JOURNEY:
    - Last-mile cab booking before arrival
    - Feedback collection with rewards
    - Loyalty point calculation and tier updates
    - Journey analytics for the user

Key Innovation:
    The "Emergency Intercept Protocol" - when a train delay exceeds a threshold,
    the agent autonomously finds the nearest alternative transport and presents
    it to the user BEFORE they need to ask.

Integration:
    - Extends: BaseAgent (agent swarm framework)
    - Uses: SupplyInfusionEngine (for alternatives), StationAmenityService (for food/lounge)
    - Reads: LiveStatusService, DelayPredictor, EmergencyServices
    - Events: EventBus for real-time notifications
"""

import logging
import asyncio
import uuid
import time
from datetime import datetime, timedelta, date
from typing import Dict, List, Any, Optional
from dataclasses import dataclass, field
from collections import defaultdict, deque
from enum import Enum

from services.agents.base_agent import BaseAgent, AgentPriority

logger = logging.getLogger("agent.shadow_guide")


# =========================================================================
# MODELS
# =========================================================================

class GuidePhase(str, Enum):
    """Current phase of the Shadow Guide lifecycle."""
    SEARCHING = "searching"      # User is searching for journeys
    BOOKED = "booked"            # Journey booked, waiting for departure
    PRE_DEPARTURE = "pre_departure"  # < 2 hours before departure
    IN_TRANSIT = "in_transit"    # User is on the train
    TRANSFER = "transfer"        # At a transfer station
    ARRIVING = "arriving"        # < 30 min from destination
    COMPLETED = "completed"      # Journey complete


class AlertPriority(str, Enum):
    """Priority of guide alerts."""
    INFO = "info"                # General info
    SUGGESTION = "suggestion"    # Helpful suggestion
    WARNING = "warning"          # Something needs attention
    URGENT = "urgent"            # Immediate action needed
    EMERGENCY = "emergency"      # Safety-critical


@dataclass
class GuideAlert:
    """An alert generated by the Shadow Guide."""
    alert_id: str
    priority: AlertPriority
    title: str
    message: str
    action_type: str = "none"     # "none", "book", "switch", "call", "navigate"
    action_data: Dict[str, Any] = field(default_factory=dict)
    expires_at: Optional[datetime] = None
    is_read: bool = False
    created_at: datetime = field(default_factory=datetime.utcnow)


@dataclass
class JourneyContext:
    """Complete context for a user's journey that the Shadow Guide tracks."""
    user_id: str
    journey_id: str
    source: str
    destination: str
    travel_date: date
    departure_time: Optional[datetime] = None
    arrival_time: Optional[datetime] = None
    train_number: Optional[str] = None
    booking_class: str = "SL"
    passenger_count: int = 1
    phase: GuidePhase = GuidePhase.SEARCHING
    pnr: Optional[str] = None

    # Live tracking
    current_location: Optional[str] = None
    last_known_delay_minutes: int = 0
    is_delayed: bool = False

    # Services booked
    food_orders: List[Dict] = field(default_factory=list)
    lounge_bookings: List[Dict] = field(default_factory=list)
    cab_bookings: List[Dict] = field(default_factory=list)

    # Alert history
    alerts: List[GuideAlert] = field(default_factory=list)

    # Preferences (learned over time)
    food_preferences: List[str] = field(default_factory=list)
    preferred_seat: str = "window"
    is_vegetarian: bool = False
    needs_wheelchair: bool = False


@dataclass
class FoodSuggestion:
    """Food suggestion based on journey context."""
    item_name: str
    vendor: str
    station_code: str
    price: float
    category: str           # "meal", "snack", "beverage", "hydration"
    reason: str             # Why this is suggested
    available_at: Optional[datetime] = None
    is_healthy: bool = False
    is_vegetarian: bool = False


# =========================================================================
# SHADOW GUIDE AGENT
# =========================================================================

class ShadowGuideAgent(BaseAgent):
    """
    Autonomous journey companion that stays with the user from search to arrival.

    This agent is the user-facing manifestation of the Sovereign Intelligence layer.
    While EDR and SIE work at the network level, the Shadow Guide works at the
    individual user level, translating system-wide decisions into personal guidance.
    """

    name = "ShadowGuideAgent"
    description = "Autonomous journey companion - monitors, alerts, and assists from booking to arrival."
    category = "user_experience"
    priority = AgentPriority.HIGH
    icon = "#"  # Avoiding emoji for terminal compatibility
    color = "#6366F1"  # Indigo
    version = "1.0.0"
    max_retries = 2
    execution_timeout = 15.0
    auto_schedule_interval = 60.0  # Check every 60 seconds

    # Configuration
    DELAY_WARNING_THRESHOLD = 30     # minutes
    DELAY_EMERGENCY_THRESHOLD = 120  # minutes
    FOOD_PREORDER_WINDOW = 60        # minutes before station arrival
    CAB_PREBOOK_WINDOW = 45          # minutes before final arrival

    # Weather conditions that trigger alerts
    WEATHER_ALERT_CONDITIONS = ["heavy_rain", "fog", "storm", "extreme_heat"]

    def __init__(self):
        super().__init__()
        self._active_journeys: Dict[str, JourneyContext] = {}
        self._food_cache: Dict[str, List[FoodSuggestion]] = {}
        self._intercept_cooldown: Dict[str, datetime] = {}  # Prevent alert spam

    # =====================================================================
    # AGENT LIFECYCLE
    # =====================================================================

    async def execute(self, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        """
        Main execution loop. Called periodically by the agent orchestrator.

        Scans all active journeys and generates alerts/actions as needed.
        """
        if not context:
            context = {}

        results = {
            "journeys_monitored": 0,
            "alerts_generated": 0,
            "actions_taken": 0,
        }

        for journey_id, journey in list(self._active_journeys.items()):
            try:
                alerts = await self._monitor_journey(journey)
                results["alerts_generated"] += len(alerts)
                results["journeys_monitored"] += 1

                # Execute any automatic actions
                for alert in alerts:
                    if alert.action_type != "none":
                        await self._execute_action(alert, journey)
                        results["actions_taken"] += 1

            except Exception as e:
                logger.error(f"[ShadowGuide] Error monitoring journey {journey_id}: {e}")

        return {
            "status": "success",
            "summary": (
                f"Monitored {results['journeys_monitored']} journeys, "
                f"generated {results['alerts_generated']} alerts, "
                f"took {results['actions_taken']} actions"
            ),
            **results,
        }

    # =====================================================================
    # JOURNEY MANAGEMENT
    # =====================================================================

    async def attach_to_journey(self, journey: JourneyContext):
        """Attach the Shadow Guide to a user's journey."""
        self._active_journeys[journey.journey_id] = journey
        logger.info(
            f"[ShadowGuide] Attached to journey {journey.journey_id}: "
            f"{journey.source}->{journey.destination} on {journey.travel_date}"
        )

        # Generate initial guidance
        initial_alerts = await self._generate_pre_journey_guidance(journey)
        journey.alerts.extend(initial_alerts)

    async def detach_from_journey(self, journey_id: str):
        """Detach the Shadow Guide after journey completion."""
        journey = self._active_journeys.pop(journey_id, None)
        if journey:
            # Generate post-journey summary
            summary = self._generate_journey_summary(journey)
            logger.info(f"[ShadowGuide] Detached from journey {journey_id}: {summary}")

    def get_journey(self, journey_id: str) -> Optional[JourneyContext]:
        """Get the current context for a journey."""
        return self._active_journeys.get(journey_id)

    # =====================================================================
    # MONITORING ENGINE
    # =====================================================================

    async def _monitor_journey(self, journey: JourneyContext) -> List[GuideAlert]:
        """Monitor a journey and generate relevant alerts."""
        alerts = []

        if journey.phase == GuidePhase.BOOKED:
            alerts.extend(await self._monitor_booked_phase(journey))

        elif journey.phase == GuidePhase.PRE_DEPARTURE:
            alerts.extend(await self._monitor_pre_departure(journey))

        elif journey.phase == GuidePhase.IN_TRANSIT:
            alerts.extend(await self._monitor_in_transit(journey))

        elif journey.phase == GuidePhase.ARRIVING:
            alerts.extend(await self._monitor_arriving(journey))

        return alerts

    async def _monitor_booked_phase(self, journey: JourneyContext) -> List[GuideAlert]:
        """Monitor during booked phase (before day of travel)."""
        alerts = []

        # Check if departure is approaching
        if journey.departure_time:
            hours_to_departure = (
                journey.departure_time - datetime.utcnow()
            ).total_seconds() / 3600

            if hours_to_departure <= 2:
                journey.phase = GuidePhase.PRE_DEPARTURE
                alerts.append(GuideAlert(
                    alert_id=f"pre_dep_{uuid.uuid4().hex[:8]}",
                    priority=AlertPriority.INFO,
                    title="Departure Approaching",
                    message=(
                        f"Your train {journey.train_number or 'N/A'} departs in "
                        f"{int(hours_to_departure * 60)} minutes from {journey.source}. "
                        f"Platform information will be updated shortly."
                    ),
                ))

        return alerts

    async def _monitor_pre_departure(self, journey: JourneyContext) -> List[GuideAlert]:
        """Monitor during pre-departure phase (< 2 hours)."""
        alerts = []

        # Check for delays
        delay = await self._check_train_delay(journey)
        if delay > self.DELAY_WARNING_THRESHOLD:
            journey.is_delayed = True
            journey.last_known_delay_minutes = delay

            if delay >= self.DELAY_EMERGENCY_THRESHOLD:
                # EMERGENCY INTERCEPT
                alert = await self._trigger_emergency_intercept(journey, delay)
                if alert:
                    alerts.append(alert)
            else:
                alerts.append(GuideAlert(
                    alert_id=f"delay_{uuid.uuid4().hex[:8]}",
                    priority=AlertPriority.WARNING,
                    title=f"Train Delayed by {delay} Minutes",
                    message=(
                        f"Your train is running {delay} minutes late. "
                        f"New expected departure: {self._format_delayed_time(journey, delay)}. "
                        f"Would you like to explore the station lounge while waiting?"
                    ),
                    action_type="book",
                    action_data={"type": "lounge", "station": journey.source},
                ))

        # Food pre-ordering suggestion
        if journey.departure_time:
            mins_to_departure = (journey.departure_time - datetime.utcnow()).total_seconds() / 60
            if 30 <= mins_to_departure <= 60:
                food = await self._suggest_food(journey, journey.source)
                if food:
                    alerts.append(GuideAlert(
                        alert_id=f"food_{uuid.uuid4().hex[:8]}",
                        priority=AlertPriority.SUGGESTION,
                        title="Pre-order Your Meal",
                        message=(
                            f"Pre-order {food[0].item_name} from {food[0].vendor} "
                            f"(Rs {int(food[0].price)}) - {food[0].reason}"
                        ),
                        action_type="book",
                        action_data={"type": "food", "items": [f.item_name for f in food]},
                    ))

        return alerts

    async def _monitor_in_transit(self, journey: JourneyContext) -> List[GuideAlert]:
        """Monitor during the journey itself."""
        alerts = []

        # Check live delay
        delay = await self._check_train_delay(journey)
        journey.last_known_delay_minutes = delay

        # Emergency intercept for severe delays
        if delay >= self.DELAY_EMERGENCY_THRESHOLD:
            if not self._is_intercept_on_cooldown(journey.journey_id):
                alert = await self._trigger_emergency_intercept(journey, delay)
                if alert:
                    alerts.append(alert)

        # Upcoming station food ordering
        next_station = await self._get_next_major_station(journey)
        if next_station:
            mins_to_station = await self._estimate_time_to_station(journey, next_station)
            if self.FOOD_PREORDER_WINDOW - 15 <= mins_to_station <= self.FOOD_PREORDER_WINDOW:
                food = await self._suggest_food(journey, next_station)
                if food:
                    alerts.append(GuideAlert(
                        alert_id=f"food_transit_{uuid.uuid4().hex[:8]}",
                        priority=AlertPriority.SUGGESTION,
                        title=f"Order Food at {next_station}",
                        message=(
                            f"Your train reaches {next_station} in ~{int(mins_to_station)} min. "
                            f"Order now for platform delivery."
                        ),
                        action_type="book",
                        action_data={"type": "food", "station": next_station},
                    ))

        # Check if approaching destination
        if journey.arrival_time:
            mins_to_arrival = (journey.arrival_time - datetime.utcnow()).total_seconds() / 60
            if mins_to_arrival <= 30:
                journey.phase = GuidePhase.ARRIVING

        return alerts

    async def _monitor_arriving(self, journey: JourneyContext) -> List[GuideAlert]:
        """Monitor during arrival phase."""
        alerts = []

        # Auto-book last-mile cab
        if not journey.cab_bookings:
            alerts.append(GuideAlert(
                alert_id=f"cab_{uuid.uuid4().hex[:8]}",
                priority=AlertPriority.SUGGESTION,
                title="Book Your Ride Home",
                message=(
                    f"You'll arrive at {journey.destination} soon. "
                    f"Book a cab now to avoid the queue."
                ),
                action_type="book",
                action_data={
                    "type": "cab",
                    "pickup": journey.destination,
                    "estimated_arrival": journey.arrival_time.isoformat() if journey.arrival_time else None,
                },
            ))

        return alerts

    # =====================================================================
    # EMERGENCY INTERCEPT PROTOCOL
    # =====================================================================

    async def _trigger_emergency_intercept(
        self, journey: JourneyContext, delay_minutes: int
    ) -> Optional[GuideAlert]:
        """
        PATENT INNOVATION: Emergency Intercept Protocol.

        When a train is severely delayed or stranded, this protocol:
        1. Finds the nearest alternative transport
        2. Calculates cost and time for the alternative
        3. Presents a one-tap switch option to the user
        4. If accepted, handles the entire rebooking automatically
        """
        try:
            from core.sovereign.supply_infusion import supply_infusion

            # Find alternatives from current location
            current = journey.current_location or journey.source
            result = await supply_infusion.evaluate_and_infuse(
                source=current,
                destination=journey.destination,
                corridor_pressure=0.98,  # Emergency level
                travel_date=journey.travel_date,
                user_tier="ELITE",  # Emergency unlocks all modes
            )

            if not result.has_alternatives:
                return None

            # Pick the best option
            best = result.options[0] if result.options else None
            if not best:
                return None

            # Set cooldown
            self._intercept_cooldown[journey.journey_id] = datetime.utcnow() + timedelta(minutes=30)

            return GuideAlert(
                alert_id=f"intercept_{uuid.uuid4().hex[:8]}",
                priority=AlertPriority.EMERGENCY,
                title=f"EMERGENCY: {delay_minutes}min Delay - Alternative Found",
                message=(
                    f"Your train is delayed by {delay_minutes} minutes. "
                    f"We found a {best.mode.value} alternative via {best.provider}: "
                    f"{best.source} to {best.destination} in {best.duration_minutes} min "
                    f"(Rs {int(best.fare)}). Tap to switch."
                ),
                action_type="switch",
                action_data={
                    "type": "emergency_switch",
                    "alternative_id": best.option_id,
                    "mode": best.mode.value,
                    "provider": best.provider,
                    "fare": best.fare,
                    "duration": best.duration_minutes,
                },
            )

        except Exception as e:
            logger.error(f"[ShadowGuide] Emergency intercept failed: {e}")
            return None

    def _is_intercept_on_cooldown(self, journey_id: str) -> bool:
        """Check if we recently sent an intercept alert."""
        cooldown_until = self._intercept_cooldown.get(journey_id)
        if cooldown_until and datetime.utcnow() < cooldown_until:
            return True
        return False

    # =====================================================================
    # PRE-JOURNEY GUIDANCE
    # =====================================================================

    async def _generate_pre_journey_guidance(self, journey: JourneyContext) -> List[GuideAlert]:
        """Generate initial guidance when Shadow Guide attaches."""
        alerts = []

        # Weather check
        weather = await self._check_weather(journey.destination, journey.travel_date)
        if weather.get("alert"):
            alerts.append(GuideAlert(
                alert_id=f"weather_{uuid.uuid4().hex[:8]}",
                priority=AlertPriority.WARNING,
                title=f"Weather Alert: {weather.get('condition', 'Unknown')}",
                message=f"Expected weather at {journey.destination}: {weather.get('description', '')}. Plan accordingly.",
            ))

        # Crowd prediction
        try:
            from core.sovereign.network_pressure import network_pressure
            corridor = await network_pressure.get_corridor_pressure(journey.source, journey.destination)
            if corridor.pressure_score > 0.80:
                alerts.append(GuideAlert(
                    alert_id=f"crowd_{uuid.uuid4().hex[:8]}",
                    priority=AlertPriority.INFO,
                    title="High Demand Expected",
                    message=(
                        f"The {journey.source}->{journey.destination} corridor is experiencing "
                        f"high demand. Arrive at the station 30 minutes early."
                    ),
                ))
        except Exception:
            pass

        # Station amenity info
        alerts.append(GuideAlert(
            alert_id=f"amenity_{uuid.uuid4().hex[:8]}",
            priority=AlertPriority.INFO,
            title=f"Station Guide: {journey.source}",
            message=(
                f"Your departure station {journey.source} has lounge access, "
                f"food court, charging stations, and free WiFi. "
                f"Tap to explore amenities."
            ),
            action_type="navigate",
            action_data={"type": "station_amenities", "station": journey.source},
        ))

        return alerts

    # =====================================================================
    # FOOD & COMFORT INTELLIGENCE
    # =====================================================================

    async def _suggest_food(
        self, journey: JourneyContext, station: str
    ) -> List[FoodSuggestion]:
        """Generate context-aware food suggestions."""
        now = datetime.utcnow() + timedelta(hours=5, minutes=30)  # IST
        hour = now.hour

        suggestions = []

        # Time-based suggestions
        if 6 <= hour <= 9:
            suggestions.append(FoodSuggestion(
                item_name="South Indian Breakfast Thali",
                vendor="Station Food Court",
                station_code=station,
                price=120,
                category="meal",
                reason="Perfect morning meal to start your journey",
                is_vegetarian=True,
                is_healthy=True,
            ))
        elif 12 <= hour <= 14:
            suggestions.append(FoodSuggestion(
                item_name="Full Meal Thali (Veg/Non-Veg)",
                vendor="IRCTC e-Catering",
                station_code=station,
                price=250,
                category="meal",
                reason="Lunch time - hot, fresh meal delivered to your seat",
                is_vegetarian=journey.is_vegetarian,
            ))
        elif 16 <= hour <= 18:
            suggestions.append(FoodSuggestion(
                item_name="Chai + Samosa Combo",
                vendor="Platform Vendor",
                station_code=station,
                price=40,
                category="snack",
                reason="Evening snack break",
                is_vegetarian=True,
            ))

        # Weather-based hydration
        suggestions.append(FoodSuggestion(
            item_name="Mineral Water (1L)",
            vendor="Station Store",
            station_code=station,
            price=20,
            category="hydration",
            reason="Stay hydrated during your journey",
            is_healthy=True,
            is_vegetarian=True,
        ))

        return suggestions[:3]

    # =====================================================================
    # DATA PROVIDERS (abstracted for integration)
    # =====================================================================

    async def _check_train_delay(self, journey: JourneyContext) -> int:
        """Check current delay for the train."""
        try:
            # In production: LiveStatusService.get_delay(train_number)
            # Simulated for now
            return journey.last_known_delay_minutes
        except Exception:
            return 0

    async def _get_next_major_station(self, journey: JourneyContext) -> Optional[str]:
        """Get the next major station on the route."""
        # In production: query route schedule
        return None

    async def _estimate_time_to_station(
        self, journey: JourneyContext, station: str
    ) -> int:
        """Estimate minutes until train reaches a station."""
        return 60  # Placeholder

    async def _check_weather(self, station: str, travel_date: date) -> Dict[str, Any]:
        """Check weather for a destination."""
        # In production: weather API integration
        return {"alert": False, "condition": "clear", "description": "Clear skies expected"}

    def _format_delayed_time(self, journey: JourneyContext, delay: int) -> str:
        """Format the delayed departure time."""
        if journey.departure_time:
            delayed = journey.departure_time + timedelta(minutes=delay)
            return delayed.strftime("%H:%M")
        return "Unknown"

    # =====================================================================
    # POST-JOURNEY
    # =====================================================================

    def _generate_journey_summary(self, journey: JourneyContext) -> Dict[str, Any]:
        """Generate a post-journey summary."""
        return {
            "journey_id": journey.journey_id,
            "route": f"{journey.source}->{journey.destination}",
            "total_alerts": len(journey.alerts),
            "delays_encountered": journey.last_known_delay_minutes > 0,
            "max_delay_minutes": journey.last_known_delay_minutes,
            "food_orders": len(journey.food_orders),
            "cab_bookings": len(journey.cab_bookings),
        }

    # =====================================================================
    # ACTION EXECUTOR
    # =====================================================================

    async def _execute_action(self, alert: GuideAlert, journey: JourneyContext):
        """Execute an automatic action from an alert."""
        action = alert.action_data

        if alert.action_type == "book" and action.get("type") == "lounge":
            try:
                from services.station_amenity_service import get_station_amenity_service
                amenity_svc = get_station_amenity_service()
                booking = await amenity_svc.book_waiting(
                    passenger_id=journey.user_id,
                    station_code=action["station"],
                    package_id="standard_wait",
                    start_time=datetime.utcnow(),
                )
                journey.lounge_bookings.append({"booking_id": booking.booking_id})
                logger.info(f"[ShadowGuide] Auto-booked lounge for journey {journey.journey_id}")
            except Exception as e:
                logger.warning(f"[ShadowGuide] Lounge booking failed: {e}")

        elif alert.action_type == "switch":
            logger.info(
                f"[ShadowGuide] Emergency switch suggested for {journey.journey_id}: "
                f"{action.get('mode')} via {action.get('provider')}"
            )

# Singleton
shadow_guide = ShadowGuideAgent()
